Free disk space
InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction pull request #70
Opened 2023-10-30 20:41 UTC by thewtex

2023-10-30 21:22 UTC, tbirdso requested changes

2023-10-30 21:22 UTC, tbirdso commented on .github/workflows/build-test-cxx.yml
> +      uses: jlumbroso/free-disk-space@main
For safety reasons let's use a tagged version.
```suggestion
      uses: jlumbroso/free-disk-space@v1.3.1
```

2023-10-30 21:22 UTC, tbirdso commented on .github/workflows/build-test-package-python.yml
> +      uses: jlumbroso/free-disk-space@main
```suggestion
      uses: jlumbroso/free-disk-space@v1.3.1
```

2023-10-30 21:22 UTC, tbirdso commented on .github/workflows/build-test-package-python.yml
> +      uses: jlumbroso/free-disk-space@main
```suggestion
      uses: jlumbroso/free-disk-space@v1.3.1
```

2023-10-30 21:22 UTC, tbirdso commented on .github/workflows/build-test-package-python.yml
> +      uses: jlumbroso/free-disk-space@main
```suggestion
      uses: jlumbroso/free-disk-space@v1.3.1
```

2023-10-30 21:22 UTC, tbirdso commented
xref https://github.com/InsightSoftwareConsortium/ITKSplitComponents/pull/74

2023-10-31 18:58 UTC, thewtex commented
Also needs updates in #69

2023-11-01 12:11 UTC, tbirdso commented
Closing in favor of https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/pull/69 .

2023-11-01 12:11 UTC, closed without merging